import ClickRings from "@/components/click-rings";
import Navigation from "@/components/navigation";
import Shockwave from "@/components/shockwave";
import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import { ViewTransition } from "react";
import "./globals.css";

const inter = Inter_Tight({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased bg-background min-h-screen font-sans`}
      >
        <Shockwave />
        <div className="pt-36 px-36 flex w-full">
          <Navigation />
          <main className="w-[calc(100%-12rem)] mx-auto max-w-3xl">
            <ViewTransition default="crossfade">{children}</ViewTransition>
          </main>
        </div>
      </body>
    </html>
  );
}
